//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeEase.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeEase.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not found or does not belong to the user..
        /// </summary>
        public static string AddressNotFoundOrUnauthorized {
            get {
                return ResourceManager.GetString("AddressNotFoundOrUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment time must be in the future..
        /// </summary>
        public static string AppointmentTimeMustBeFuture {
            get {
                return ResourceManager.GetString("AppointmentTimeMustBeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasePlatformService with ID {0} not found or inactive..
        /// </summary>
        public static string BasePlatformServiceNotFound {
            get {
                return ResourceManager.GetString("BasePlatformServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasePlatformService with ID {0} not found or inactive for one of the services..
        /// </summary>
        public static string BasePlatformServiceNotFoundForService {
            get {
                return ResourceManager.GetString("BasePlatformServiceNotFoundForService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base platform service with ID {0} not found or inactive..
        /// </summary>
        public static string BasePlatformServiceNotFoundOrInactive {
            get {
                return ResourceManager.GetString("BasePlatformServiceNotFoundOrInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cancel a completed or already cancelled booking..
        /// </summary>
        public static string BookingCancellationNotAllowed {
            get {
                return ResourceManager.GetString("BookingCancellationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking must be completed to leave a review..
        /// </summary>
        public static string BookingMustBeCompleted {
            get {
                return ResourceManager.GetString("BookingMustBeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only pending bookings can be confirmed..
        /// </summary>
        public static string BookingMustBePending {
            get {
                return ResourceManager.GetString("BookingMustBePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking not found..
        /// </summary>
        public static string BookingNotFound {
            get {
                return ResourceManager.GetString("BookingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A review already exists for this booking..
        /// </summary>
        public static string BookingReviewAlreadyExists {
            get {
                return ResourceManager.GetString("BookingReviewAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authorized to review this booking..
        /// </summary>
        public static string BookingUnauthorizedUser {
            get {
                return ResourceManager.GetString("BookingUnauthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update a completed or cancelled booking..
        /// </summary>
        public static string BookingUpdateNotAllowed {
            get {
                return ResourceManager.GetString("BookingUpdateNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer address is required for home service..
        /// </summary>
        public static string CustomerAddressRequiredForHomeService {
            get {
                return ResourceManager.GetString("CustomerAddressRequiredForHomeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete admin: {0}.
        /// </summary>
        public static string DeleteAdminFailed {
            get {
                return ResourceManager.GetString("DeleteAdminFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect..
        /// </summary>
        public static string IncorrectCurrentPassword {
            get {
                return ResourceManager.GetString("IncorrectCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired code..
        /// </summary>
        public static string InvalidOrExpiredOtp {
            get {
                return ResourceManager.GetString("InvalidOrExpiredOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating must be between 1.0 and 5.0..
        /// </summary>
        public static string InvalidReviewRating {
            get {
                return ResourceManager.GetString("InvalidReviewRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found on the platform..
        /// </summary>
        public static string PlatformServiceNotFound {
            get {
                return ResourceManager.GetString("PlatformServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider is not available at the selected time..
        /// </summary>
        public static string ProviderNotAvailableAtThisTime {
            get {
                return ResourceManager.GetString("ProviderNotAvailableAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider with ID {0} not found..
        /// </summary>
        public static string ProviderNotFound {
            get {
                return ResourceManager.GetString("ProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider is not available at the selected time..
        /// </summary>
        public static string ProviderUnavailable {
            get {
                return ResourceManager.GetString("ProviderUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review not found..
        /// </summary>
        public static string ReviewNotFound {
            get {
                return ResourceManager.GetString("ReviewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found..
        /// </summary>
        public static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to cancel this booking..
        /// </summary>
        public static string UnauthorizedBookingCancellation {
            get {
                return ResourceManager.GetString("UnauthorizedBookingCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to update this booking..
        /// </summary>
        public static string UnauthorizedBookingUpdate {
            get {
                return ResourceManager.GetString("UnauthorizedBookingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to delete this review..
        /// </summary>
        public static string UnauthorizedReviewDelete {
            get {
                return ResourceManager.GetString("UnauthorizedReviewDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to update this review..
        /// </summary>
        public static string UnauthorizedReviewUpdate {
            get {
                return ResourceManager.GetString("UnauthorizedReviewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not an admin..
        /// </summary>
        public static string UserNotAdmin {
            get {
                return ResourceManager.GetString("UserNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with ID {0} not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Email {0} not found..
        /// </summary>
        public static string UserNotFoundByEmail {
            get {
                return ResourceManager.GetString("UserNotFoundByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP code is valid..
        /// </summary>
        public static string ValidOtp {
            get {
                return ResourceManager.GetString("ValidOtp", resourceCulture);
            }
        }
    }
}
